# Generated by Django 5.2.7 on 2025-10-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='desc',
        ),
    ]
